### PR TITLE
Add PrivateStorage payment server

### PR DESCRIPTION
**Pull request by hacklschorsch**
This adds the PrivateStorage Payment Server to the public services page.

The API delivers error messages for all but correct queries - maybe a "tcp-ping" check would be more apt, if those errors are interpreted as being "down" by upptime?

### CODE REVIEW

**Comment by hacklschorsch** [comment]
Sorry @btlogy I didn't know creating an MR with a different branch would have an effect to the public page :/

**Comment by btlogy** [comment]
> Sorry @btlogy I didn't know creating an MR with a different branch would have an effect to the public page :/

Yeah, I've been there too indeed.
Something else I may have to document in LeastAuthority/it-ops#355, because it's not natural to me to commit in the master :-/:

I'm not sure we can prevent to create branches...
We might have to filter the worflows to avoid building on other branch than the master.
I would be surprise no one else has bumped into this...

**Comment by btlogy** [comment]
It's not going to be so easy: workflows will be overwritten by daily updates of the template:

https://github.com/LeastAuthority/end-users-upptime/blob/master/.github/workflows/setup.yml#L1-L14

I'm trying to disabling it anyway, so we can merge w/o all those extra commits: see #4

**Comment by btlogy** [comment]
Closed in favor of #4

**Pull request closed without merging**
